# Generated by Django 2.2.5 on 2019-09-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
